// insertRibbonKnot
global proc insertRibbonKnot() {


string $selobj[] = `ls -o -sl`;
string $selcmpt[] = `ls -sl`;
string $tokenBuffer[];
string $cmpnt = "";
if (size($selcmpt)>0){
	tokenize $selcmpt[0] "." $tokenBuffer;

for ($i=1;$i<size($tokenBuffer);$i++){
	$cmpnt = $cmpnt + "." + $tokenBuffer[$i];
}
$base = `match "[a-zA-Z]*" $selobj[0]`;


select -r ($base+"1"+$cmpnt);
select -add ($base+"2"+$cmpnt);
}
else {
	error ("Select a Curve");
}

}