// masterWorkshop
global proc masterWorkshop() {
	string $filename = `file -q -sn`;	string $tokenBuffer[];	string $tokenBuffer2[];	int $i = 0;	$numTokens = `tokenize $filename "/" $tokenBuffer`;
	print ("tokens:"+$numTokens);	// get parent folder as pathname	string $outputPath = ("/"+$tokenBuffer[0]);	for ($i=1;$i<($numTokens-2);$i++){		$outputPath = ($outputPath+"/"+$tokenBuffer[$i]);	}	print ($outputPath+"\n");		string $sceneName = `file -q -shn -sn`;	string $tokenBuffer2[];	$numTokens = `tokenize $sceneName "_" $tokenBuffer2`;	$outputFilename = ($tokenBuffer2[0]+"_"+$tokenBuffer2[1]+"_master.ma");	print ($outputFilename+"\n");	// import all references	$ref = `file -q -r`;	print ($ref[0]+"\n");		if (size($ref)>0){		for ($each in $ref){			//$RefName = `file -q -rfn $each`;			file -ir $each;		}	} 	// save file	file -rename ($outputPath + "/" + $outputFilename);	file -save -type "mayaAscii";	

}